### ISSUE TITLE
"Unable to fetch dashboard" after migration to Laminas

### ISSUE THREAD

**Issue by permiakov** [laminas-api-tools/api-tools-admin-ui#19]
Hey, guys. I successfully migrated the project from Zend to Laminas and I got all my integration tests working.

But the Admin UI application shows the error "Unable to fetch dashboard" and I don't see my Services there(dashboard request receives 403 forbidden as I see in Network tools). 

When I try to save new API it says " I cannot create the API module, please enter a valid name (alpha characters)" and(module request receives 403 forbidden also).

Thanks for the tips!

**Comment by michalbundyra** [comment]
Hi @permiakov,

we haven't experienced that issue before. Could you please check what version of laminas-api-tools/api-tools-admin-ui are you using? We had some issues with rewrite and that's why version 1.3.14 has been released. If you are on any previous version I encourage you to update first, with all other laminas dependencies and try again.

**Comment by permiakov** [comment]
"name": "laminas-api-tools/api-tools",
            "version": "1.4.1",

 "name": "laminas-api-tools/api-tools-admin-ui",
            "version": "1.3.14",

**Comment by permiakov** [comment]
I suppose the migration tool sets latest versions of all packages?

**Comment by michalbundyra** [comment]
@permiakov 

> I suppose the migration tool sets latest versions of all packages?

Yes and no ;)
In most cases yes, as we are not changing requirements in composer, just rename packages - so in most cases it is updated to the latest version as we are removing lock file and running `composer install`.
For the same reason it might not update to the latest version, if the requirements are for the fixed version or there is additional restriction.

It looks like you are on the latest versions so all should be fine. Would you be able to investigate it a bit more (xdebug/check where is the issue). It will be very helpful... Thanks!

**Comment by permiakov** [comment]
It's quite big chain of packages, any hints/places where to put breakpoint?

**Comment by weierophinney** [comment]
A status code of 403 indicates an authorization error. Do you have "deny_by_default" enabled in your authorization settings, by any chance?

**Comment by permiakov** [comment]
Hi @weierophinney . I didn't have **deny_by_default** in my application, but you made a good point that brought me to the right place. I have a custom legacy authorization piece of code that had exception for Apigility admin tool requests containing '/apigility/' in the path, that by obvious reason was not replaced to '/api-tools'.

Thanks a lot for the help, guys!
